# permissions for end users to view beerlogdeploys.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: beerlogdeploy-viewer-role
rules:
- apiGroups:
  - labs.linuxtips.io
  resources:
  - beerlogdeploys
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - labs.linuxtips.io
  resources:
  - beerlogdeploys/status
  verbs:
  - get
